#ifndef ORDER_MATCHING_ENGINE_ORDER_TYPE_HPP
#define ORDER_MATCHING_ENGINE_ORDER_TYPE_HPP

enum class OrderType {
    Limit,
    Market,
    IOC,
    FOK
};

#endif // ORDER_MATCHING_ENGINE_ORDER_TYPE_HPP
